### PR TITLE
Updates documentation around color modification

### PR DESCRIPTION
**Pull request by chadedrupt**
Documents changes made in this PR https://github.com/getconnect/connect-js/pull/54/files

### CODE REVIEW

**Comment by richard-kong** [comment]
`select` and `aggregations` used interchangeably in chart colors section, these mean the same thing the same term should be used to be consistent.
I, personally, had problems understanding what `select` actually was. A code sample would help.

**Comment by chadedrupt** [comment]
How about this Rich?

**Comment by richard-kong** [comment]
`aggregation` is still mentioned in the note about legends. Assuming the links to aggregations and group will work once we deploy this change, I don't see any other problems.

**Comment by chadedrupt** [comment]
Cool, updated that as well

**Pull request merged**
